newlines

diff --git a/vircs b/vircs
--- a/vircs
+++ b/vircs
@@ -33,17 +33,38 @@
 ################################################################################
 
 # Dependencies.
-RCS=`which rcs`		|| { echo "rcs command not found"; exit 1 }
+RCS=`which rcs` || {
+	echo "rcs command not found"
+	exit 1
+}
 CI="${RCS} ci"
 CO="${RCS} co"
 DIFF="${RCS} diff"
 CLEAN="${RCS} clean"
-CHGRP=`which chgrp`	|| { echo "chgrp command not found"; exit 1 }
-CHMOD=`which chmod`	|| { echo "chmod command not found"; exit 1 }
-CHOWN=`which chown`	|| { echo "chown command not found"; exit 1 }
-FILE=`which file`	|| { echo "file command not found"; exit 1 }
-RM=`which rm`		|| { echo "rm command not found"; exit 1 }
-STAT=`which stat`	|| { echo "stat command not found"; exit 1 }
+CHGRP=`which chgrp` || {
+	echo "chgrp command not found"
+	exit 1
+}
+CHMOD=`which chmod` || {
+	echo "chmod command not found"
+	exit 1
+}
+CHOWN=`which chown` || {
+	echo "chown command not found"
+	exit 1
+}
+FILE=`which file` || {
+	echo "file command not found"
+	exit 1
+}
+RM=`which rm` || {
+	echo "rm command not found"
+	exit 1
+}
+STAT=`which stat` || {
+	echo "stat command not found"
+	exit 1
+}
 [ -z "${EDITOR}" ] && {
 	# Real sysadmins use vim. ;)
 	echo "Environment variable EDITOR not set; we'll use vim."
